ttsx/backweb/urls.py
from django.conf.urls import url

from backweb import views

urlpatterns = [
    url(r'^login/', views.login, name='login'),
    url(r'^index/', views.index, name='index'),
    url(r'^logout/', views.logout, name='logout'),
    url(r'^addclassify/', views.addclassify, name='addclassify'),
    url(r'^goods/', views.goods, name='goods'),
    url(r'^addgoods/', views.addgoods, name='addgoods'),
    url(r'^upclassification/', views.upclassification, name='upclassification'),
    url(r'^carousel/', views.carousel, name='carousel'),
    url(r'^static/', views.static, name='static'),
    url(r'^pattern/', views.pattern, name='pattern'),
    url(r'^addpattern/', views.addpattern, name='addpattern'),
    url(r'^goods_recommend/', views.goods_recommend, name='goods_recommend'),
    url(r'^goods_new/', views.goods_new, name='goods_new'),
    url(r'^goods_del/', views.goods_del, name='goods_del'),
    url(r'^order/', views.order, name='order'),
    url(r'^uporder/', views.uporder, name='uporder'),
    url(r'^user_show/', views.user_show, name='user_show'),
    url(r'^is_root/', views.is_root, name='is_root'),
    url(r'^distribution/', views.distribution, name='distribution'),
    url(r'^adddistribution/', views.adddistribution, name='adddistribution'),
]

ttsx/ttsx/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import static

from ttsx import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^web/', include('web.urls', namespace='web')),
    url(r'^backweb/', include('backweb.urls', namespace='backweb')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ttsx/web/urls.py
from django.conf.urls import url

from web import views

urlpatterns = [
    url(r'^index/', views.index, name='index'),
    url(r'^login/', views.login, name='login'),
    url(r'^logout/', views.logout, name='logout'),
    url(r'^register/', views.register, name='register'),
    url(r'^goodslist/(?P<page>\d+)/(?P<class_f>\d+)/(?P<subclass>[0\u4e00-\u9fa5]+)/(?P<price_state>\d+)/(?P<popularity_state>\d+)/', views.goodslist, name='goodslist'),
    url(r'^goods/', views.goods, name='goods'),
    url(r'^upshopping/', views.upshopping, name='upshopping'),
    url(r'^shopping/', views.shopping, name='shopping'),
    url(r'^addshopping/', views.addshopping, name='addshopping'),
    url(r'^cutshopping/', views.cutshopping, name='cutshopping'),
    url(r'^delshopping/', views.delshopping, name='delshopping'),
    url(r'^check/', views.check, name='check'),
    url(r'^total/', views.total, name='total'),
    url(r'^check_all/', views.check_all, name='check_all'),

    url(r'^dispose_order/', views.dispose_order, name='dispose_order'),
    url(r'^order/', views.order, name='order'),
    url(r'^uporder/', views.uporder, name='uporder'),
    url(r'^user_center_info/', views.user_center_info, name='user_center_info'),
    url(r'^user_center_order/', views.user_center_order, name='user_center_order'),
    url(r'^user_center_site/', views.user_center_site, name='user_center_site'),
    url(r'^check_address/', views.check_address, name='check_address'),
    url(r'^show_site/', views.show_site, name='show_site'),
    url(r'^del_site/', views.del_site, name='del_site'),
]

ttsx/backweb/models.py
from django.db import models

# Create your models here.

ttsx/backweb/views.py
from datetime import datetime, timedelta

from django.contrib.auth.hashers import check_password
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render

from django.urls import reverse

from utils.functions import random_session
from web.models import User, UserSession, ClassiFication, Goods, Carousel, Static, Pattern, Order, Distribution


def login(request):
    if request.method == 'GET':
        return render(request, 'backweb/login.html')
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        if not all([username, password]):
            return render(request, 'backweb/login.html', {'error': '输入不能为空'})

        user = User.objects.filter(username=username).first()
        if not user:
            return render(request, 'backweb/login.html', {'error': '用户不存在'})
        if not check_password(password, user.password):
            return render(request, 'backweb/login.html', {'error': '密码不正确'})
        if not user.is_root:
            return render(request, 'backweb/login.html', {'error': '该用户不是管理员'})

        res = HttpResponseRedirect(reverse('backweb:index'))
        session = random_session()
        out_time = datetime.now() + timedelta(days=1)
        res.set_cookie('session', session, expires=out_time)
        UserSession.objects.create(user=user,
                                   session=session,
                                   out_time=out_time)

        UserSession.objects.filter(Q(user=user) & ~Q(session=session)).delete()
        return res


def index(request):
    if request.method == 'GET':
        return render(request, 'backweb/index.html')


def logout(request):
    if request.method == 'GET':
        user = request.user
        UserSession.objects.filter(user=user).delete()

        res = HttpResponseRedirect(reverse('backweb:login'))
        res.delete_cookie('session')
        return res


def addclassify(request):
    if request.method == 'GET':
        return render(request, 'backweb/addclassify.html')
    if request.method == 'POST':
        typename = request.POST.get('typename')
        childtypenames = request.POST.get('childtypenames')
        classimg = request.FILES.get('classimg')

        if not all([typename, childtypenames, classimg]):
            return render(request, 'backweb/addclassify.html', {'error': '输入不能为空'})
        ClassiFication.objects.create(typename=typename,
                                      childtypenames=childtypenames,
                                      classimg=classimg)
        return HttpResponseRedirect(reverse('backweb:addclassify'))


def goods(request):
    if request.method == 'GET':
        page_num = int(request.GET.get('page', 1))
        goods = Goods.objects.all()
        paginator = Paginator(goods, 10)
        goods_page = paginator.page(page_num)

        return render(request, 'backweb/goods.html', {'goods_page': goods_page})


def addgoods(request):
    if request.method == 'GET':
        goods_id = request.GET.get('goods_id', False)
        if goods_id:
            goods = Goods.objects.get(id=goods_id)
        else:
            goods = goods_id
        return render(request, 'backweb/addgoods.html', {'goods': goods})
    if request.method == 'POST':
        id = request.POST.get('id')
        goodsname = request.POST.get('goodsname')
        price = request.POST.get('price')
        norms = request.POST.get('norms')
        classify = request.POST.get('classify')
        subclass = request.POST.get('subclass')
        abstract = request.POST.get('abstract')
        commodity = request.POST.get('commodity')
        is_recommend = request.POST.get('is_recommend')
        is_new = request.POST.get('is_new')
        goodsimg = request.FILES.get('goodsimg')

        try:
            price = float(price)
        except:
            return render(request, 'backweb/addgoods.html', {'error': '填写价格不正确，请输入数字'})

        if not is_recommend:
            is_recommend = False
        else:
            is_recommend = True

        if not is_new:
            is_new = False
        else:
            is_new = True

        if id:
            if not all([goodsname, price, norms, classify, subclass, abstract, commodity]):
                return render(request, 'backweb/addgoods.html', {'error': '填写不完整'})

            class_f_id = ClassiFication.objects.get(typename=classify).id

            Goods.objects.filter(id=id).update(goodsname=goodsname,
                                               price=price,
                                               norms=norms,
                                               classify=classify,
                                               subclass=subclass,
                                               abstract=abstract,
                                               commodity=commodity,
                                               is_recommend=is_recommend,
                                               class_f_id=class_f_id,
                                               is_new=is_new)
            if goodsimg:
                Goods.objects.filter(id=id).update(goodsimg=goodsimg)
            return HttpResponseRedirect(reverse('backweb:goods'))
        else:
            if not all([goodsname, price, norms, classify, subclass, abstract, commodity, goodsimg]):
                return render(request, 'backweb/addgoods.html', {'error': '填写不完整'})

            class_f_id = ClassiFication.objects.get(typename=classify).id

            Goods.objects.create(goodsname=goodsname,
                                 price=price,
                                 norms=norms,
                                 classify=classify,
                                 subclass=subclass,
                                 abstract=abstract,
                                 commodity=commodity,
                                 is_recommend=is_recommend,
                                 goodsimg=goodsimg,
                                 class_f_id=class_f_id,
                                 is_new=is_new)
            return HttpResponseRedirect(reverse('backweb:addgoods'))


def upclassification(request):
    if request.method == 'GET':
        classi = ClassiFication.objects.all()
        data = {
            'classiname': [cla.typename for cla in classi]
        }
        return JsonResponse({'code': 200, 'msg': '请求成功', 'data': data})
    if request.method == 'POST':
        classiname = request.POST.get('classi_name')
        classi = ClassiFication.objects.filter(typename=classiname).first()
        data = {
            'child': classi.childtypenames.split('#')
        }
        return JsonResponse({'code': 200, 'msg': '请求成功', 'data': data})


def carousel(request):
    if request.method == 'GET':
        classs = ClassiFication.objects.all()
        return render(request, 'backweb/carousel.html', {'classs': classs})
    if request.method == 'POST':
        classi_id = request.POST.get('classi_id')
        order = request.POST.get('order')
        img = request.FILES.get('img')
        if not all([classi_id, order, img]):
            return render(request, 'backweb/carousel.html', {'error': '填写不能为空'})

        Carousel.objects.create(classi_id=classi_id, img=img, order=order)
        return HttpResponseRedirect(reverse('backweb:carousel'))


def static(request):
    if request.method == 'GET':
        classs = ClassiFication.objects.all()
        return render(request, 'backweb/static.html', {'classs': classs})
    if request.method == 'POST':
        classi_id = request.POST.get('classi_id')
        order = request.POST.get('order')
        img = request.FILES.get('img')
        if not all([classi_id, order, img]):
            return render(request, 'backweb/carousel.html', {'error': '填写不能为空'})

        Static.objects.create(classi_id=classi_id, img=img, order=order)
        return HttpResponseRedirect(reverse('backweb:static'))


def pattern(request):
    if request.method == 'GET':
        return render(request, 'backweb/pattern.html')


def addpattern(request):
    if request.method == 'GET':
        return render(request, 'backweb/addpattern.html')
    if request.method == 'POST':
        pattname = request.POST.get('pattname')
        describe = request.POST.get('describe')
        if not all([pattname, describe]):
            return render(request, 'backweb/addpattern.html', {'error': '填写不能为空'})

        Pattern.objects.create(pattname=pattname, describe=describe)
        return HttpResponseRedirect(reverse('backweb:addpattern'))


def goods_recommend(request):
    if request.method == 'POST':
        goods_id = request.POST.get('goods_id')
        goods = Goods.objects.get(id=goods_id)
        judge = goods.is_recommend
        if judge:
            judge = goods.is_recommend = False
        else:
            judge = goods.is_recommend = True
        goods.save()
        return JsonResponse({'code': 200, 'msg': '请求成功', 'judge': judge})


def goods_new(request):
    if request.method == 'POST':
        goods_id = request.POST.get('goods_id')
        goods = Goods.objects.get(id=goods_id)
        judge = goods.is_new
        if judge:
            judge = goods.is_new = False
        else:
            judge = goods.is_new = True
        goods.save()
        return JsonResponse({'code': 200, 'msg': '请求成功', 'judge': judge})


def goods_del(request):
    if request.method == 'POST':
        goods_id = request.POST.get('goods_id')
        Goods.objects.get(id=goods_id).delete()

        return JsonResponse({'code': 200, 'msg': '请求成功'})


def order(request):
    if request.method == 'GET':
        page_num = int(request.GET.get('page', 1))
        orders_all = Order.objects.filter(status=1)
        # Paginator给对象分一页多少个
        paginator = Paginator(orders_all, 5)
        # .page赋哪一页
        orders = paginator.page(page_num)

ttsx/templates/backweb/addclassify.html
{% extends 'base_back.html' %}

{% block title %}
    添加分类
{% endblock %}

{% block content %}
<section class="rt_wrap content mCustomScrollbar">
 <div class="rt_content">
      <div class="page_title">
       <h2 class="fl">添加分类</h2>
      </div>
     <form method="post" enctype="multipart/form-data">
         {% csrf_token %}
         {{ error }}
      <ul class="ulColumn2">
       <li>
        <span class="item_name" style="width:120px;">上传图片：</span>
        <label class="uploadImg">
         <input type="file" name="classimg"/>
         <span>上传图片</span>
        </label>
       </li>
       <li>
        <span class="item_name" style="width:120px;">分类名称：</span>
        <input name="typename" type="text" class="textbox textbox_225" placeholder="分类名称..."/>
       </li>
       <li>
        <span class="item_name" style="width:120px;">子分类：</span>
        <input name="childtypenames" type="text" class="textbox textbox_225" placeholder="子分类..."/>
       <span class="errorTips">分类之间用#相隔</span>
       </li>
       <li>
        <span class="item_name" style="width:120px;"></span>
        <input type="submit" class="link_btn" value="提交"/>
       </li>
      </ul>
      </form>
 </div>
</section>
{% endblock %}

ttsx/templates/backweb/adddistribution.html
{% extends 'base_back.html' %}

{% block title %}
    添加配送方式
{% endblock %}

{% block content %}
<section class="rt_wrap content mCustomScrollbar">
 <div class="rt_content">
      <div class="page_title">
       <h2 class="fl">添加配送方式</h2>
      </div>
     <form method="post" enctype="multipart/form-data">
         {% csrf_token %}
         {{ error }}
      <ul class="ulColumn2">
       <li>
        <span class="item_name" style="width:120px;">配送方式名：</span>
        <input name="distname" type="text" class="textbox textbox_225" placeholder="配送方式名..."/>
       </li>
       <li>
        <span class="item_name" style="width:120px;">配送描述：</span>
        <textarea name="describe" placeholder="配送描述..." class="textarea" style="width:500px;height:100px;"></textarea>
       </li>
       <li>
        <span class="item_name" style="width:120px;"></span>
        <input type="submit" class="link_btn" value="提交"/>
       </li>
      </ul>
     </form>
 </div>
</section>
{% endblock %}

ttsx/templates/backweb/addgoods.html
{% extends 'base_back.html' %}

{% block title %}
    添加商品
{% endblock %}

{% block content %}
<section class="rt_wrap content mCustomScrollbar">
 <div class="rt_content">
      <div class="page_title">
       <h2 class="fl">添加商品</h2>
      </div>
     <form method="post" enctype="multipart/form-data">
         {% csrf_token %}
         {{ error }}
      <ul class="ulColumn2">
      <input value="{{ goods.id }}" name="id" type="text" hidden/>
       <li>
        <span class="item_name" style="width:120px;">商品名字：</span>
        <input value="{{ goods.goodsname }}" name="goodsname" type="text" class="textbox textbox_225" placeholder="商品名字..."/>
       </li>
       <li>
        <span class="item_name" style="width:120px;">上传图片：</span>
        <label class="uploadImg">
         <input type="file" name="goodsimg"/>
         <span>上传图片</span>
        </label>
       </li>
       <li>
        <span class="item_name" style="width:120px;">价格：</span>
        <input value="{{ goods.price }}" name="price" type="text" class="textbox textbox_225" placeholder="价格..."/>
       </li>
       <li>
        <span class="item_name" style="width:120px;">规格：</span>
        <input value="{{ goods.norms }}" name="norms" type="text" class="textbox textbox_225" placeholder="规格..."/>
       </li>
          <script>
              (function () {
                  $.get('/backweb/upclassification', function (msg) {
                      s = ''
                      for(var i = 0;i < msg.data.classiname.length; i += 1){
                          class_name = msg.data.classiname[i]
                          s += '<option value="' + class_name + '"'
                          if ('{{ goods.classify }}'==class_name){
                              s += 'selected'
                          }
                          s += '>' + class_name + '</option>'
                      }
                      $('#classify').html(s)
                      childtypenames()
                  })
              })();
              function childtypenames() {
                  var classi_name = document.getElementById("classify").value;
                  var csrf = $('input[name="csrfmiddlewaretoken"]').val()
                  $.ajax({
                      url:'/backweb/upclassification/',
                      dataType:'json',
                      type:'POST',
                      data:{
                          'classi_name':classi_name,
                      },
                      headers:{'X-CSRFToken': csrf},
                      success:function (msg) {
                          s = ''
                          for(var i = 0;i < msg.data.child.length; i += 1) {
                              child_name = msg.data.child[i]
                              s += '<option value="' + child_name + '"'
                              if ('{{ goods.subclass }}'==child_name){
                              s += 'selected'
                              }
                              s += '>' + child_name + '</option>'
                          }
                          $('#subclass').html(s)
                      }
                  })
              }
          </script>
       <li>
        <span class="item_name" style="width:120px;">分类：</span>
        <select class="select" name="classify" id="classify" onchange="childtypenames()">
        </select>
       </li>
       <li>
        <span class="item_name" style="width:120px;">子分类：</span>
        <select class="select" name="subclass" id="subclass">
        </select>
       </li>
       <li>
        <span class="item_name" style="width:120px;">简要说明：</span>
        <input value="{{ goods.abstract }}" name="abstract" type="text" class="textbox textbox_295" placeholder="简要说明..."/>
       </li>
       <li>
        <span class="item_name" style="width:120px;">商品详情：</span>
        <textarea name="commodity" placeholder="商品详情..." class="textarea" style="width:500px;height:100px;">{{ goods.commodity }}</textarea>
       </li>
       <li>
        <span class="item_name" style="width:120px;">推荐：</span>
        <label class="single_selection"><input type="checkbox" name="is_recommend"
        {% if goods.is_recommend %}
            checked
        {% endif %}
        />是否推荐&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="checkbox" name="is_new"
        {% if goods.is_new %}
            checked
        {% endif %}
        />是否新品</label>
       </li>
       <li>
        <span class="item_name" style="width:120px;"></span>
        <input type="submit" class="link_btn" value="提交"/>
       </li>
      </ul>
     </form>
 </div>
</section>
{% endblock %}

ttsx/templates/backweb/addpattern.html
{% extends 'base_back.html' %}

{% block title %}
    添加支付方式
{% endblock %}

{% block content %}
<section class="rt_wrap content mCustomScrollbar">
 <div class="rt_content">
      <div class="page_title">
       <h2 class="fl">添加支付方式</h2>
      </div>
     <form method="post" enctype="multipart/form-data">
         {% csrf_token %}
         {{ error }}
      <ul class="ulColumn2">
       <li>
        <span class="item_name" style="width:120px;">支付方式名：</span>
        <input name="pattname" type="text" class="textbox textbox_225" placeholder="支付方式名..."/>
       </li>
       <li>
        <span class="item_name" style="width:120px;">支付描述：</span>
        <textarea name="describe" placeholder="支付描述..." class="textarea" style="width:500px;height:100px;"></textarea>
       </li>
       <li>
        <span class="item_name" style="width:120px;"></span>
        <input type="submit" class="link_btn" value="提交"/>
       </li>
      </ul>
     </form>
 </div>
</section>
{% endblock %}

ttsx/templates/backweb/carousel.html
{% extends 'base_back.html' %}

{% block title %}
    添加轮播图
{% endblock %}

{% block content %}
<section class="rt_wrap content mCustomScrollbar">
 <div class="rt_content">
      <div class="page_title">
       <h2 class="fl">添加轮播图</h2>
      </div>
     <form method="post" enctype="multipart/form-data">
         {% csrf_token %}
         {{ error }}
      <ul class="ulColumn2">
       <li>
        <span class="item_name" style="width:120px;">分类：</span>
        <select class="select" name="classi_id" id="subclass">
            {% for class in classs %}
            <option value="{{ class.id }}">{{ class.typename }}</option>
            {% endfor %}
        </select>
       </li>
       <li>
        <span class="item_name" style="width:120px;">上传图片：</span>
        <label class="uploadImg">
         <input type="file" name="img"/>
         <span>上传图片</span>
        </label>
       </li>
      <li>
        <span class="item_name" style="width:120px;">轮播顺序：</span>
        <input name="order" type="text" class="textbox textbox_225" placeholder="轮播顺序..."/>
       </li>
       <li>
        <span class="item_name" style="width:120px;"></span>
        <input type="submit" class="link_btn" value="提交"/>
       </li>
      </ul>
     </form>
 </div>
</section>
{% endblock %}

ttsx/templates/backweb/distribution.html
{% extends 'base_back.html' %}

{% block title %}
{% endblock %}

{% block content %}
    {% load static %}
<section class="rt_wrap content mCustomScrollbar">
 <div class="rt_content">
      <div class="page_title">
       <h2 class="fl">配送方式</h2>
       <a href="{% url 'backweb:adddistribution' %}" class="fr top_rt_btn add_icon">添加配送方式</a>
      </div>
      <table class="table">
       <tr>
        <th>缩略图</th>
        <th>快递名称</th>
        <th>快递描述</th>
        <th>操作</th>
       </tr>
       <tr>
        <td class="center"><img src="upload/shentong.png" width="165" height="65"/></td>
        <td>申通快递</td>
        <td><p>上海申通物流公司拥有247个独立城市营业所，179个营业厅，1220个操作点，快递初创于1993年，是一家以经营快递为主的国内合资（民营）企业。</p></td>
        <td class="center">
         <a href="product_detail.html" title="编辑" class="link_icon">&#101;</a>
         <a href="#" title="删除" class="link_icon">&#100;</a>
        </td>
       </tr>
       <tr>
        <td class="center"><img src="upload/yuantong.png" width="165" height="65"/></td>
        <td>圆通快递</td>
        <td><p>圆通速递创建于2000年5月28日,经过近十四年的发展,已成为一家集速递、航空、电子商务等业务为一体的大型企业集团,形成了集团化、网络化、规模化、品牌化经营的新...</p></td>
        <td class="center">
         <a href="product_detail.html" title="编辑" class="link_icon">&#101;</a>
         <a href="#" title="删除" class="link_icon">&#100;</a>
        </td>
       </tr>
       <tr>
        <td class="center"><img src="upload/yunda.png" width="165" height="65"/></td>
        <td>韵达快递</td>
        <td><p>“韵达快递”品牌创立于1999年8月，总部位于中国上海，现已成为集快递、物流、电子商务配送和仓储服务为一体的全国网络型品牌快递企业，服务范围覆盖国内31个省（区、市）及港澳台地区。</p></td>
        <td class="center">
         <a href="product_detail.html" title="编辑" class="link_icon">&#101;</a>
         <a href="#" title="删除" class="link_icon">&#100;</a>
        </td>
       </tr>
      </table>
 </div>
</section>
{% endblock %}

ttsx/templates/backweb/order.html
{% extends 'base_back.html' %}

{% block title %}
    订单处理
{% endblock %}

{% block content %}
    {% load static %}
<section class="rt_wrap content mCustomScrollbar">
 <div class="rt_content">
      <div class="page_title">
       <h2 class="fl">订单处理示例</h2>
      </div>
      <script>
          function uporder(order_id){
              var csrf = $('input[name="csrfmiddlewaretoken"]').val()
              var distribution_id = $('#select_distribution option:selected').val();
              $.ajax({
                  url:'/backweb/uporder/',
                  dataType:'json',
                  type:'POST',
                  data:{
                      'order_id': order_id,
                      'distribution_id': distribution_id,
                  },
                  headers:{'X-CSRFToken': csrf},
                  success:function (msg) {
                      if(msg.code==200){
                          $('#order_' + order_id).remove()
                      }
                  }
              })
          }
      </script>
      <table class="table">
      {% csrf_token %}
       <tr>
        <th>订单号</th>
        <th>收件人</th>
        <th>联系电话</th>
        <th>收件人地址</th>
        <th>支付方式</th>
        <th>创建时间</th>
        <th>选择配送方式</th>
        <th>操作</th>
       </tr>
       {% for order in orders %}
       <tr id="order_{{ order.id }}">
        <td class="center" style="word-wrap:break-word;word-break:break-all;">{{ order.order_number }}</td>
        <td>{{ order.usersite.addressee }}</td>
        <td>{{ order.usersite.mobile }}</td>
        <td>
         <address>{{ order.usersite.site }}</address>
        </td>
        <td class="center">{{ order.pattern.pattname }}</td>
        <td class="center">{{ order.creation_time|date:"Y-m-d H:i:s" }}</td>
        <td class="center mode_distribution">
            <select id="select_distribution">
                {% for distribution in distributions %}
                    <option value ="{{ distribution.id }}">{{ distribution.distname }}</option>
                {% endfor %}
            </select>
        </td>
        <td class="center">
         <a onclick="uporder({{ order.id }})" title="确认订单" class="link_icon" target="_blank">&#118;</a>
        </td>
       </tr>
       {% endfor %}
      </table>
      <aside class="paging">
      {% if orders.has_previous %}
      <a href="{% url 'backweb:order' %}?page={{ orders.previous_page_number }}">上一页</a>
      {% endif %}

      <a href="{% url 'backweb:order' %}">第一页</a>

      {% for i in orders.paginator.page_range %}
      <a href="{% url 'backweb:order' %}?page={{ i }}">{{ i }}</a>
      {% endfor %}

      <a href="{% url 'backweb:order' %}?page={{ orders.paginator.num_pages }}">最后一页</a>

      {% if orders.has_next %}
      <a href="{% url 'backweb:order' %}?page={{ orders.next_page_number }}">下一页</a>
      {% endif %}
      </aside>
 </div>
</section>
{% endblock %}

ttsx/templates/backweb/user_show.html
{% extends 'base_back.html' %}

{% block title %}
    用户列表
{% endblock %}

{% block content %}
    {% load static %}
<section class="rt_wrap content mCustomScrollbar">
 <div class="rt_content">
      <div class="page_title">
       <h2 class="fl">用户列表示例</h2>
      </div>
      <script>
          function is_root(user_id) {
              $.get('/backweb/is_root', {user_id: user_id}, function (msg) {
                  if(msg.code == 200){
                      if (msg.is_root){
                          $('#user_' + msg.user_id).html('<a title="是" class="link_icon" onclick="is_root(' + msg.user_id + ')">&#89;</a>')
                      }else{
                          $('#user_' + msg.user_id).html('<a title="否" class="link_icon" onclick="is_root(' + msg.user_id + ')">&#88;</a>')
                      }
                  }
              })
          }
      </script>
      <table class="table">
       <tr>
        <th>用户名</th>
        <th>邮箱</th>
        <th>是否管理员</th>
       </tr>

       {% for user in users %}
       <tr>
        <td class="center">{{ user.username }}</td>
        <td class="center">{{ user.email }}</td>
        <td class="center" id="user_{{ user.id }}">
            {% if user.is_root %}
                <a title="是" class="link_icon" onclick="is_root({{ user.id }})">&#89;</a>
            {% else %}
                <a title="否" class="link_icon" onclick="is_root({{ user.id }})">&#88;</a>
            {% endif %}
        </td>
       </tr>
       {% endfor %}

      </table>
      <aside class="paging">
      {% if users.has_previous %}
      <a href="{% url 'backweb:user_show' %}?page={{ users.previous_page_number }}">上一页</a>
      {% endif %}

      <a href="{% url 'backweb:user_show' %}">第一页</a>

      {% for i in users.paginator.page_range %}
      <a href="{% url 'backweb:user_show' %}?page={{ i }}">{{ i }}</a>
      {% endfor %}

      <a href="{% url 'backweb:user_show' %}?page={{ users.paginator.num_pages }}">最后一页</a>

      {% if users.has_next %}
      <a href="{% url 'backweb:user_show' %}?page={{ users.next_page_number }}">下一页</a>
      {% endif %}

      </aside>
 </div>
</section>
{% endblock %}