ttsx/ttsx/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import static

from ttsx import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^web/', include('web.urls', namespace='web')),
    url(r'^backweb/', include('backweb.urls', namespace='backweb')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ttsx/web/urls.py
from django.conf.urls import url

from web import views

urlpatterns = [
    url(r'^index/', views.index, name='index'),
    url(r'^login/', views.login, name='login'),
    url(r'^logout/', views.logout, name='logout'),
    url(r'^register/', views.register, name='register'),
    url(r'^goodslist/(?P<page>\d+)/(?P<class_f>\d+)/(?P<subclass>[0\u4e00-\u9fa5]+)/(?P<price_state>\d+)/(?P<popularity_state>\d+)/', views.goodslist, name='goodslist'),
    url(r'^goods/', views.goods, name='goods'),
    url(r'^upshopping/', views.upshopping, name='upshopping'),
    url(r'^shopping/', views.shopping, name='shopping'),
    url(r'^addshopping/', views.addshopping, name='addshopping'),
    url(r'^cutshopping/', views.cutshopping, name='cutshopping'),
    url(r'^delshopping/', views.delshopping, name='delshopping'),
    url(r'^check/', views.check, name='check'),
    url(r'^total/', views.total, name='total'),
    url(r'^check_all/', views.check_all, name='check_all'),

    url(r'^dispose_order/', views.dispose_order, name='dispose_order'),
    url(r'^order/', views.order, name='order'),
    url(r'^uporder/', views.uporder, name='uporder'),
    url(r'^user_center_info/', views.user_center_info, name='user_center_info'),
    url(r'^user_center_order/', views.user_center_order, name='user_center_order'),
    url(r'^user_center_site/', views.user_center_site, name='user_center_site'),
    url(r'^check_address/', views.check_address, name='check_address'),
    url(r'^show_site/', views.show_site, name='show_site'),
    url(r'^del_site/', views.del_site, name='del_site'),
]

ttsx/web/models.py
from django.db import models

# Create your models here.


class User(models.Model):
    username = models.CharField(max_length=16, unique=True)
    password = models.CharField(max_length=256)
    email = models.CharField(max_length=64, unique=True)
    is_root = models.BooleanField(default=0)  # 是否管理员

    class Meta:
        db_table = 'user'


class ClassiFication(models.Model):
    classimg = models.ImageField(upload_to='class')  # 分类图片
    typename = models.CharField(max_length=16)  # 商品分类名称
    childtypenames = models.CharField(max_length=200)  # 商品子分类名称

    class Meta:
        db_table = 'classification'


class Goods(models.Model):
    goodsname = models.CharField(max_length=50, unique=True)  # 商品名字
    goodsimg = models.ImageField(upload_to='goods')  # 图片
    price = models.FloatField()  # 价格
    norms = models.CharField(max_length=20)  # 规格
    abstract = models.CharField(max_length=100)  # 简要说明
    commodity = models.TextField()  # 商品详情
    classify = models.CharField(max_length=16)  # 分类名称
    class_f = models.ForeignKey(ClassiFication)
    subclass = models.CharField(max_length=16)  # 子分类名称
    is_recommend = models.BooleanField(default=0)  # 是否推荐
    is_new = models.BooleanField(default=0)  # 是否新品
    popularity = models.IntegerField(default=0)  # 销量

    class Meta:
        db_table = 'goods'


class UserSite(models.Model):
    user = models.ForeignKey(User)  # 用户
    addressee = models.CharField(max_length=20)  # 收件人
    site = models.CharField(max_length=50)  # 详细地址
    postcode = models.CharField(max_length=20)  # 邮政编码
    mobile = models.CharField(max_length=20)  # 手机
    default_site = models.BooleanField(default=True)  # 默认地址

    class Meta:
        db_table = 'usersite'


class Shopping(models.Model):
    user = models.ForeignKey(User)  # 关联用户
    goods = models.ForeignKey(Goods)  # 关联商品
    goods_num = models.IntegerField(default=1)  # 商品个数
    is_select = models.BooleanField(default=True)  # 是否选择商品

    class Meta:
        db_table = 'shopping'


class Pattern(models.Model):
    pattname = models.CharField(max_length=30)  # 支付名字
    pattimg = models.ImageField(null=True, upload_to='pattern')  # 图片
    describe = models.CharField(max_length=1000)  # 简介

    class Meta:
        db_table = 'pattern'


class Distribution(models.Model):
    distname = models.CharField(max_length=30)  # 配送名字
    distimg = models.ImageField(upload_to='dist')  # 图片
    describe = models.CharField(max_length=1000)  # 简介

    class Meta:
        db_table = 'distribution'


class Order(models.Model):
    order_number = models.CharField(max_length=50)  # 订单号
    user = models.ForeignKey(User)  # 关联用户
    # 0 已下单，未付款， 1 已付款, 未发货,  2 已付款，已发货
    status = models.IntegerField(default=0)  # 状态
    pattern = models.ForeignKey(Pattern, null=True)
    distribution = models.ForeignKey(Distribution, null=True)
    creation_time = models.DateTimeField(auto_now_add=True)
    usersite = models.ForeignKey(UserSite, null=True)

    class Meta:
        db_table = 'order'


class Order_Goods(models.Model):
    goods = models.ForeignKey(Goods)  # 关联的商品
    order = models.ForeignKey(Order)  # 关联的订单
    goods_num = models.IntegerField(default=1)  # 商品的个数

    class Meta:
        db_table = 'order_goods'


class UserSession(models.Model):
    user = models.ForeignKey(User)  # 关联用户
    session = models.CharField(max_length=256)  # Session
    out_time = models.DateTimeField()  # 过期时间

    class Meta:
        db_table = 'usersession'


class Carousel(models.Model):
    img = models.ImageField(upload_to='carousel')  # 图片
    classi = models.ForeignKey(ClassiFication)  # 名称
    order = models.IntegerField(unique=True)  # 播放顺序

    class Meta:
        db_table = 'carousel'


class Static(models.Model):
    img = models.ImageField(upload_to='carousel')  # 图片
    classi = models.ForeignKey(ClassiFication)  # 名称
    order = models.IntegerField(unique=True)  # 播放顺序

    class Meta:
        db_table = 'static'


class Browse(models.Model):
    user = models.ForeignKey(User)  # 用户
    goods = models.OneToOneField(Goods)  # 商品
    browse_time = models.DateTimeField(auto_now_add=True)  # 浏览时间

    class Meta:
        db_table = 'browse'

ttsx/templates/web/goodslist.html
{% extends 'base.html' %}
{% block title %}
    天天生鲜-商品列表
{% endblock %}

{% block content %}
    <div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>
				<span></span>
				<ul class="subnav">
                    {% for classi in classis %}
					<li><a href="{% url 'web:goodslist' 1 classi.id 0 0 0 %}" class="{{ classi.type }}">{{ classi.typename }}</a></li>
                    {% endfor %}
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="{% url 'web:index' %}">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="breadcrumb">
    {% csrf_token %}
		<a href="{% url 'web:goodslist' 1 0 0 0 0 %}">全部分类</a>
        {% if class_f != '0' %}
		<span>></span>
		<a href="{% url 'web:goodslist' 1 class_f 0 0 0 %}">{{ goodall.0.classify }}</a>
        {% endif %}
        {% if subclass != '0' %}
            <span>></span>
		    <a href="{% url 'web:goodslist' 1 class_f subclass 0 0 %}">{{ subclass }}</a>
        {% endif %}
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
                    {% for good in goodslook %}
                        {% if good.is_new %}
					<li>
						<a href="{% url 'web:goods' %}?goods_id={{ good.id }}"><img src="/media/{{ good.goodsimg }}"></a>
						<h4><a href="{% url 'web:goods' %}?goods_id={{ good.id }}">{{ good.goodsname }}</a></h4>
						<div class="prize">￥{{ good.price }}</div>
					</li>
                        {% endif %}
                    {% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<div class="sort_bar">
				<a href="#" class="active">默认</a>
				<a href="{% url 'web:goodslist' 1 class_f subclass alt_price_state 0 %}">
                    价格
                    {% if price_state == '1' %}
                        ↓
                    {% elif price_state == '2' %}
                        ↑
                    {% endif %}
                </a>
				<a href="{% url 'web:goodslist' 1 class_f subclass 0 alt_popularity_state %}">
                    人气
                    {% if popularity_state == '1' %}
                        ↓
                    {% elif popularity_state == '2' %}
                        ↑
                    {% endif %}
                </a>
			</div>

			<ul class="goods_type_list clearfix">
                {% for good in goods %}
				<li>
					<a href="{% url 'web:goods' %}?goods_id={{ good.id }}"><img src="/media/{{ good.goodsimg }}"></a>
					<h4><a href="{% url 'web:goods' %}?goods_id={{ good.id }}">{{ good.goodsname }}</a></h4>
					<div class="operate">
						<span class="prize">￥{{ good.price }}</span>
						<span class="unit">{{ good.price }}/{{ good.norms }}</span>
						<a onclick="upshopping({{ good.id }})" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
                {% endfor %}
			</ul>
        <script>
            function upshopping(goods_id) {
                var csrf = $('input[name="csrfmiddlewaretoken"]').val()
                $.ajax({
                    url:'/web/upshopping/',
                    type:'POST',
                    dataType:'json',
                    data:{
                        'goods_id': goods_id,
                        'goods_num': 1,
                    },
                    headers:{'X-CSRFToken': csrf},
                    success: function (msg) {
                        $('#show_count').html(msg.count)
                    },
                })
            }
        </script>

			<div class="pagenation">
                {% if goods.has_previous %}
				<a href="{% url 'web:goodslist' goods.previous_page_number class_f subclass price_state popularity_state %}">上一页</a>
                {% endif %}

                <a href="{% url 'web:goodslist' 1 class_f subclass price_state popularity_state %}">第一页</a>

                {% for i in goods.paginator.page_range %}
				<a href="{% url 'web:goodslist' i class_f subclass price_state popularity_state %}"
                   {% if goods.number == i %}
                   class="active"
                   {% endif %}
                >{{ i }}</a>
                {% endfor %}

                <a href="{% url 'web:goodslist' goods.paginator.num_pages class_f subclass price_state popularity_state %}">最后一页</a>

                {% if goods.has_next %}
				<a href="{% url 'web:goodslist' goods.next_page_number class_f subclass price_state popularity_state %}">下一页></a>
                {% endif %}
			</div>
		</div>
	</div>
{% endblock %}

ttsx/templates/web/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    天天生鲜-首页
{% endblock %}

{% block js %}
	<script type="text/javascript" src="{% static 'web/js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'web/js/jquery-ui.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'web/js/slide.js' %}"></script>
{% endblock %}

{% block content %}
	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="{% url 'web:index' %}">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="center_con clearfix">
		<ul class="subnav fl">
            {% for classi in classis %}
			<li><a href="{% url 'web:goodslist' 1 classi.id 0 0 0 %}" class="{{ classi.type }}">{{ classi.typename }}</a></li>
            {% endfor %}
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
                {% for carousel in carousels %}
                    <li><a href="{% url 'web:goodslist' 1 carousel.classi_id 0 0 0 %}"><img src="/media/{{ carousel.img }}" alt="幻灯片"></a></li>
                {% endfor %}
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
            {% for static in statics %}
			<a href="{% url 'web:goodslist' 1 static.classi_id 0 0 0 %}"><img src="/media/{{ static.img }}"></a>
            {% endfor %}
		</div>
	</div>
    {% for classi in classis %}
	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model01">{{ classi.typename }}</h3>
			<div class="subtitle fl">
				<span>|</span>
                {% for class in classi.classlist %}
				<a href="{% url 'web:goodslist' 1 classi.id class 0 0 %}">{{ class }}</a>
                {% endfor %}
			</div>
			<a href="{% url 'web:goodslist' 1 classi.id 0 0 0 %}" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><a href="{% url 'web:goodslist' 1 classi.id 0 0 0 %}"><img src="/media/{{ classi.classimg }}"></a></div>
			<ul class="goods_list fl">
                {% for classi in classi.goods_set.all %}
                    {% if classi.is_recommend %}
				<li>
					<h4><a href="#">{{ classi.goodsname }}</a></h4>
					<a href="{% url 'web:goods' %}?goods_id={{ classi.id }}"><img src="/media/{{ classi.goodsimg }}"></a>
					<div class="prize">¥ {{ classi.price }}</div>
				</li>
                    {% endif %}
				{% endfor %}
			</ul>
		</div>
	</div>
    {% endfor %}
    {% endblock %}

	{% block end %}
	<script type="text/javascript" src="{% static 'web/js/slideshow.js' %}"></script>
	<script type="text/javascript">
		BCSlideshow('focuspic');
		var oFruit = document.getElementById('fruit_more');
		var oShownum = document.getElementById('show_count');

		var hasorder = localStorage.getItem('order_finish');

		if(hasorder)
		{
			oShownum.innerHTML = '2';
		}

		oFruit.onclick = function(){
			window.location.href = 'goodslist.html';
		}
	</script>
    {% endblock %}

ttsx/templates/web/user_center_info.html
{% extends 'base2.html' %}

{% block title %}
天天生鲜-用户中心
{% endblock %}

{% block page_name %}
    用户中心
{% endblock %}

{% block content %}
	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'web:user_center_info' %}" class="active">· 个人信息</a></li>
				<li><a href="{% url 'web:user_center_order' %}">· 全部订单</a></li>
				<li><a href="{% url 'web:user_center_site' %}">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
							<li><span>用户名：</span>{{ user.username }}</li>
							<li><span>邮箱：</span>{{ user.email }}</li>
						</ul>
				</div>
				
				<h3 class="common_title2">最近浏览</h3>
				<div class="has_view_list">
					<ul class="goods_type_list clearfix">
                {% for browse in browses %}
				<li>
					<a href="{% url 'web:goods' %}?goods_id={{ browse.goods.id }}"><img src="/media/{{ browse.goods.goodsimg }}"></a>
					<h4><a href="{% url 'web:goods' %}?goods_id={{ browse.goods.id }}">{{ browse.goods.goodsname }}</a></h4>
					<div class="operate">
						<span class="prize">￥{{ browse.goods.price }}</span>
						<span class="unit">{{ browse.goods.price }}/{{ browse.goods.norms }}</span>
						<a onclick="upshopping({{ browse.goods.id }})" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
                {% endfor %}
			</ul>
            <script>
                function upshopping(goods_id) {
                    var csrf = $('input[name="csrfmiddlewaretoken"]').val()
                    $.ajax({
                        url:'/web/upshopping/',
                        type:'POST',
                        dataType:'json',
                        data:{
                            'goods_id': goods_id,
                            'goods_num': 1,
                        },
                        headers:{'X-CSRFToken': csrf},
                    })
                }
            </script>
		</div>
		</div>
	</div>

{% endblock %}

ttsx/templates/web/user_center_order.html
{% extends 'base2.html' %}

{% block title %}
天天生鲜-用户中心
{% endblock %}

{% block page_name %}
    用户中心
{% endblock %}

{% block content %}
	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'web:user_center_info' %}">· 个人信息</a></li>
				<li><a href="{% url 'web:user_center_order' %}" class="active">· 全部订单</a></li>
				<li><a href="{% url 'web:user_center_site' %}">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
			<h3 class="common_title2">全部订单</h3>
            <script>
            $(function () {
                {% for order in orders %}
                    s = 0
                    {% for order_goods in order.order_goods_set.all %}
                        b = ({{ order_goods.goods.price }} * {{ order_goods.goods_num }}).toFixed(2)
                        $("#subtotal_{{ order.id }}_{{ order_goods.goods.id }}").html(b + '元')
                        s += parseFloat(b)
                    {% endfor %}
                    s = s.toFixed(2)
                    $("#total_{{ order.id }}").html(s + '元')
                {% endfor %}
            })
            </script>
            {% for order in orders %}
			<ul class="order_list_th w978 clearfix">
				<li class="col01">{{ order.creation_time|date:"Y-m-d H:i:s" }}</li>
				<li class="col02" style="width: 300px">订单号：{{ order.order_number }}</li>
				<li class="col02 stress">
                    {% if order.status == 0 %}
                    未支付
                    {% elif order.status == 1 %}
                    已支付
                    {% elif order.status == 2 %}
                    已发货
                    {% endif %}
                </li>
			</ul>

			<table class="order_list_table w980">
				<tbody>
					<tr>
						<td width="55%">
                            {% for order_goods in order.order_goods_set.all %}
							<ul class="order_goods_list clearfix">
								<li class="col01"><img src="/media/{{ order_goods.goods.goodsimg }}"></li>
								<li class="col02">{{ order_goods.goods.goodsname }}<em>{{ order_goods.goods.price }}元/{{ order_goods.goods.norms }}</em></li>
								<li class="col03">{{ order_goods.goods_num }}</li>
								<li class="col04" id="subtotal_{{ order.id }}_{{ order_goods.goods.id }}">元</li>
							</ul>
                            {% endfor %}
						</td>
						<td width="15%" id="total_{{ order.id }}">元</td>
						<td width="15%">
                            {% if order.status == 0 %}
                            待付款
                            {% elif order.status == 1 %}
                            已付款,待发货
                            {% elif order.status == 2 %}
                            已付款,已发货
                            {% endif %}
                        </td>
                        {% if order.status == 0 %}
                        <td width="15%"><a href="{% url 'web:order' %}?order_number={{ order.order_number }}" class="oper_btn">去付款</a>
                        {% elif order.status == 1 %}
                        <td width="15%"><a href="#" class="oper_btn">查看物流</a></td>
                        {% elif order.status == 2 %}
                        <td width="15%"><a href="#" class="oper_btn">去评价</a></td>
                        {% endif %}
					</tr>
				</tbody>
			</table>
            {% endfor %}

			<div class="pagenation">
                {% if orders.has_previous %}
                <a href="{% url 'web:user_center_order' %}?page={{ orders.previous_page_number }}">上一页</a>
                {% endif %}

                <a href="{% url 'web:user_center_order' %}">第一页</a>

                {% for i in orders.paginator.page_range %}
                <a href="{% url 'web:user_center_order' %}?page={{ i }}"
                   {% if orders.number == i %}
                       class="active"
                   {% endif %}
                >{{ i }}</a>
                {% endfor %}

                 <a href="{% url 'web:user_center_order' %}?page={{ orders.paginator.num_pages }}">最后一页</a>

                {% if orders.has_next %}
                 <a href="{% url 'web:user_center_order' %}?page={{ orders.next_page_number }}">下一页</a>
                {% endif %}
			</div>
		</div>
	</div>
{% endblock %}

ttsx/templates/web/user_center_site.html
{% extends 'base2.html' %}

{% block title %}
天天生鲜-用户中心
{% endblock %}

{% block css %}
    <style>
        .site_con > dl > dt{
            display:inline;
        }
        .site_con > dl > input{
            display:inline;
        }
        .site_con > dl > dd{
            display:inline;
        }
    </style>
{% endblock %}

{% block page_name %}
    用户中心
{% endblock %}

{% block content %}
	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'web:user_center_info' %}">· 个人信息</a></li>
				<li><a href="{% url 'web:user_center_order' %}">· 全部订单</a></li>
				<li><a href="{% url 'web:user_center_site' %}" class="active">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
        <form method="post">
        {% csrf_token %}
				<h3 class="common_title2">收货地址</h3>
				<div class="site_con" id="site_show">
				</div>
				<h3 class="common_title2" id="site_state">添加地址</h3>
				<div class="site_con">
						<div class="form_group">
							<label>收件人：</label>
							<input type="text" name="addressee" id="addressee"><span id="addressee_hint" style="color: red;display: none;">&nbsp;&nbsp;&nbsp;请填写收件人</span>
						</div>
						<div class="form_group form_group2">
							<label>详细地址：</label>
							<textarea class="site_area" name="site" id="site"></textarea><span id="site_hint" style="color: red;display: none;">&nbsp;&nbsp;&nbsp;请填写详细地址</span>
						</div>
						<div class="form_group">
							<label>邮编：</label>
							<input type="text" name="postcode" id="postcode"><span id="postcode_hint" style="color: red;display: none;">&nbsp;&nbsp;&nbsp;请填写邮编</span>
						</div>
						<div class="form_group">
							<label>手机：</label>
							<input type="text" name="mobile" id="mobile"><span id="mobile_hint" style="color: red;display: none;">&nbsp;&nbsp;&nbsp;请填写手机</span>
						</div>
						<input type="button" onclick="upsite()" value="提交" class="info_submit">
				</div>
        </form>
        <script>
            function show_site() {
                $.get('/web/show_site', function (msg) {
                    if (msg.code == 200) {
                        var s = ''
                        var usersites = msg.data.usersites
                        for (var i = 0; i < usersites.length; i += 1) {
                            s += '<dl>'
                            if (usersites[i].default_site) {
                                s += '<dt>默认地址：</dt>'
                            } else {
                                s += '<dt>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</dt>'
                            }
                            s += '<input onclick="compile(' + usersites[i].id + ')" type="radio" name="usersite_id" value="' + usersites[i].id + '">'
                            s += '<dd>' + usersites[i].site + '（' + usersites[i].addressee + '收）' + usersites[i].secrecy + '</dd>'
                            s += '<input type="button" onclick="del_site(' + usersites[i].id + ')" value="删除地址">'
                            s += '</dl>'
                        }
                        $('#site_show').html(s)
                    }
                })
            }
            show_site()
            function compile(usersite_id) {
                var csrf = $('input[name="csrfmiddlewaretoken"]').val()
                $.ajax({
                    url:'/web/check_address/',
                    dataType:'json',
                    type:'POST',
                    data:{
                        'usersite_id': usersite_id,
                    },
                    headers:{'X-CSRFToken': csrf},
                    success:function (msg) {
                        if (msg.code == 200) {
                            $('#addressee').val(msg.data.addressee)
                            $('#site').val(msg.data.site)
                            $('#postcode').val(msg.data.postcode)
                            $('#mobile').val(msg.data.mobile)
                            $('#site_state').text('编辑地址')
                        }
                    }
                })
            }
            function upsite() {
                var addressee = $('#addressee').val()
                var site = $('#site').val()
                var postcode = $('#postcode').val()
                var mobile = $('#mobile').val()
                var flag = true
                if (addressee == ''){
                    flag = false
                    $('#addressee_hint').css('display', '')
                }
                if (site == ''){
                    flag = false
                    $('#site_hint').css('display', '')
                }
                if (postcode == ''){
                    flag = false
                    $('#postcode_hint').css('display', '')
                }
                if (mobile == ''){
                    flag = false
                    $('#mobile_hint').css('display', '')
                }
                if (flag){
                    var csrf = $('input[name="csrfmiddlewaretoken"]').val()
                    var usersite_id = $('input[name="usersite_id"]:checked').val()
                    $.ajax({
                        url:'/web/user_center_site/',
                        dataType:'json',
                        type:'POST',
                        data:{
                            'usersite_id': usersite_id,
                            'addressee': addressee,
                            'site': site,
                            'postcode': postcode,
                            'mobile': mobile,
                        },
                        headers:{'X-CSRFToken': csrf},
                        success:function (msg) {
                            if (msg.code == 200) {
                                $('#addressee').val('')
                                $('#site').val('')
                                $('#postcode').val('')
                                $('#mobile').val('')
                                $('#site_state').text('添加地址')
                                show_site()
                            }
                        }
                    })
                }
            }
            function del_site(usersite_id) {
                var csrf = $('input[name="csrfmiddlewaretoken"]').val()
                $.ajax({
                    url:'/web/del_site/',
                    dataType:'json',
                    type:'POST',
                    data:{
                        'usersite_id': usersite_id,
                    },
                    headers:{'X-CSRFToken': csrf},
                    success:function (msg) {
                        if (msg.code == 200){
                            show_site()
                        }
                    }
                })
            }
        </script>
		</div>
	</div>
{% endblock %}