ttsx/backweb/urls.py
from django.conf.urls import url

from backweb import views

urlpatterns = [
    url(r'^login/', views.login, name='login'),
    url(r'^index/', views.index, name='index'),
    url(r'^logout/', views.logout, name='logout'),
    url(r'^addclassify/', views.addclassify, name='addclassify'),
    url(r'^goods/', views.goods, name='goods'),
    url(r'^addgoods/', views.addgoods, name='addgoods'),
    url(r'^upclassification/', views.upclassification, name='upclassification'),
    url(r'^carousel/', views.carousel, name='carousel'),
    url(r'^static/', views.static, name='static'),
    url(r'^pattern/', views.pattern, name='pattern'),
    url(r'^addpattern/', views.addpattern, name='addpattern'),
    url(r'^goods_recommend/', views.goods_recommend, name='goods_recommend'),
    url(r'^goods_new/', views.goods_new, name='goods_new'),
    url(r'^goods_del/', views.goods_del, name='goods_del'),
    url(r'^order/', views.order, name='order'),
    url(r'^uporder/', views.uporder, name='uporder'),
    url(r'^user_show/', views.user_show, name='user_show'),
    url(r'^is_root/', views.is_root, name='is_root'),
    url(r'^distribution/', views.distribution, name='distribution'),
    url(r'^adddistribution/', views.adddistribution, name='adddistribution'),
]

ttsx/ttsx/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import static

from ttsx import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^web/', include('web.urls', namespace='web')),
    url(r'^backweb/', include('backweb.urls', namespace='backweb')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ttsx/web/urls.py
from django.conf.urls import url

from web import views

urlpatterns = [
    url(r'^index/', views.index, name='index'),
    url(r'^login/', views.login, name='login'),
    url(r'^logout/', views.logout, name='logout'),
    url(r'^register/', views.register, name='register'),
    url(r'^goodslist/(?P<page>\d+)/(?P<class_f>\d+)/(?P<subclass>[0\u4e00-\u9fa5]+)/(?P<price_state>\d+)/(?P<popularity_state>\d+)/', views.goodslist, name='goodslist'),
    url(r'^goods/', views.goods, name='goods'),
    url(r'^upshopping/', views.upshopping, name='upshopping'),
    url(r'^shopping/', views.shopping, name='shopping'),
    url(r'^addshopping/', views.addshopping, name='addshopping'),
    url(r'^cutshopping/', views.cutshopping, name='cutshopping'),
    url(r'^delshopping/', views.delshopping, name='delshopping'),
    url(r'^check/', views.check, name='check'),
    url(r'^total/', views.total, name='total'),
    url(r'^check_all/', views.check_all, name='check_all'),

    url(r'^dispose_order/', views.dispose_order, name='dispose_order'),
    url(r'^order/', views.order, name='order'),
    url(r'^uporder/', views.uporder, name='uporder'),
    url(r'^user_center_info/', views.user_center_info, name='user_center_info'),
    url(r'^user_center_order/', views.user_center_order, name='user_center_order'),
    url(r'^user_center_site/', views.user_center_site, name='user_center_site'),
    url(r'^check_address/', views.check_address, name='check_address'),
    url(r'^show_site/', views.show_site, name='show_site'),
    url(r'^del_site/', views.del_site, name='del_site'),
]

ttsx/templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>
        {% block title %}
        {% endblock %}
    </title>
    {% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'web/css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'web/css/main.css' %}">
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
        {% block js %}
        {% endblock %}
    <script src="{% static 'web/js/functions.js' %}"></script>
</head>
<body>
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				<div class="login_btn fl">
                    {% if not user.id %}
                    <a href="{% url 'web:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'web:register' %}">注册</a>
                    {% else %}
                    欢迎您：<em>{{ user.username }}</em>
                    <span>|</span>
					<a href="{% url 'web:logout' %}">注销</a>
                    {% endif %}
				</div>
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'web:user_center_info' %}">用户中心</a>
					<span>|</span>
					<a href="{% url 'web:shopping' %}">我的购物车</a>
					<span>|</span>
					<a href="{% url 'web:user_center_order' %}">我的订单</a>
				</div>
			</div>
		</div>
	</div>
    <div class="search_bar clearfix">
		<a href="{% url 'web:index' %}" class="logo fl"><img src="{% static 'web/images/logo.png' %}"></a>
		<div class="search_con fl">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索" onclick="hunt()">
		</div>
		<div class="guest_cart fr">
			<a href="{% url 'web:shopping' %}" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">{{ count }}</div>
		</div>
	</div>

    {% block content %}
    {% endblock %}

    <div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2018 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>

    {% block end %}
    {% endblock %}
</body>
</html>

ttsx/templates/base2.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>
        {% block title %}
        {% endblock %}
    </title>
    {% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'web/css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'web/css/main.css' %}">
    {% block css %}
    {% endblock %}
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script src="{% static 'web/js/functions.js' %}"></script>
</head>
<body>
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				<div class="login_btn fl">
					{% if not user.id %}
                    <a href="{% url 'web:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'web:register' %}">注册</a>
                    {% else %}
                    欢迎您：<em>{{ user.username }}</em>
                    <span>|</span>
					<a href="{% url 'web:logout' %}">注销</a>
                    {% endif %}
				</div>
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'web:user_center_info' %}">用户中心</a>
					<span>|</span>
					<a href="{% url 'web:shopping' %}">我的购物车</a>
					<span>|</span>
					<a href="{% url 'web:user_center_order' %}">我的订单</a>
				</div>
			</div>
		</div>
	</div>

	<div class="search_bar clearfix">
		<a href="{% url 'web:index' %}" class="logo fl"><img src="{% static 'web/images/logo.png' %}"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;
            {% block page_name %}
            {% endblock %}
       </div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
	</div>

    {% block content %}
    {% endblock %}

    <div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>

    {% block end %}
    {% endblock %}
</body>
</html>

ttsx/templates/base3.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>
        {% block title %}
        {% endblock %}
    </title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'web/css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'web/css/main.css' %}">
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    {% block js %}
    {% endblock %}
</head>
<body>
    {% block content %}
    {% endblock %}
    <div class="footer no-mp">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2018 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
</body>
</html>

ttsx/templates/base_back.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<title>
    {% block title %}
    {% endblock %}
    {% load static %}
</title>
<meta name="author" content="DeathGhost" />
<link rel="stylesheet" type="text/css" href="{% static 'backweb/css/style.css' %}">
<!--[if lt IE 9]>
<script src="{% static 'backweb/js/html5.js' %}"></script>
<![endif]-->
<script src="{% static 'backweb/js/jquery.js' %}"></script>
<script src="{% static 'backweb/js/jquery.mCustomScrollbar.concat.min.js' %}"></script>
<script>

	(function($){
		$(window).load(function(){

			$("a[rel='load-content']").click(function(e){
				e.preventDefault();
				var url=$(this).attr("href");
				$.get(url,function(data){
					$(".content .mCSB_container").append(data); //load new content inside .mCSB_container
					//scroll-to appended content
					$(".content").mCustomScrollbar("scrollTo","h2:last");
				});
			});

			$(".content").delegate("a[href='top']","click",function(e){
				e.preventDefault();
				$(".content").mCustomScrollbar("scrollTo",$(this).attr("href"));
			});

		});
	})(jQuery);
</script>
</head>
<body>
<!--header-->
<header>
 <h1><img src="{% static 'backweb/images/admin_logo.png' %}"/></h1>
 <ul class="rt_nav">
  <li><a href="{% url 'web:index' %}" target="_blank" class="website_icon">站点首页</a></li>
  <li><a href="{% url 'backweb:logout' %}" class="quit_icon">安全退出</a></li>
 </ul>
</header>
<!--aside nav-->
<!--aside nav-->
<aside class="lt_aside_nav content mCustomScrollbar">
 <h2><a href="{% url 'backweb:index' %}">起始页</a></h2>
 <ul>
  <li>
   <dl>
    <dt>页面管理</dt>
    <dd><a href="{% url 'backweb:carousel' %}">轮播图</a></dd>
    <dd><a href="{% url 'backweb:static' %}">静态图</a></dd>
   </dl>
  </li>
  <li>
   <dl>
    <dt>商品管理</dt>
    <dd><a href="{% url 'backweb:addclassify' %}">添加分类</a></dd>
    <dd><a href="{% url 'backweb:goods' %}">商品列表</a></dd>
   </dl>
  </li>
  <li>
   <dl>
    <dt>配送与支付设置</dt>
    <dd><a href="{% url 'backweb:distribution' %}pay_list.html">配送方式</a></dd>
    <dd><a href="{% url 'backweb:pattern' %}">支付方式</a></dd>
   </dl>
  </li>
  <li>
   <dl>
    <dt>用户列表</dt>
    <dd><a href="{% url 'backweb:user_show' %}">用户列表</a></dd>
    <dd><a href="{% url 'backweb:order' %}">订单列表</a></dd>
   </dl>
  </li>
  <li>
   <p class="btm_infor">© DeathGhost.cn 版权所有</p>
  </li>
 </ul>
</aside>
{% block content %}
{% endblock %}
</body>
</html>